# docker-compose.yml

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    stdin_open: true
    tty: true

  data_service:
    build:
      context: .
      dockerfile: Dockerfile.data_service
